# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'video_recording.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_VideoRecording(object):
    def setupUi(self, VideoRecording):
        if not VideoRecording.objectName():
            VideoRecording.setObjectName(u"VideoRecording")
        VideoRecording.resize(763, 677)
        self.widget_2 = QWidget(VideoRecording)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 10, 741, 661))
        self.graphicsView = QGraphicsView(self.widget_2)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(170, 20, 261, 201))
        self.recording_screen_selection = QComboBox(self.widget_2)
        self.recording_screen_selection.addItem("")
        self.recording_screen_selection.addItem("")
        self.recording_screen_selection.addItem("")
        self.recording_screen_selection.setObjectName(u"recording_screen_selection")
        self.recording_screen_selection.setGeometry(QRect(30, 40, 111, 31))
        self.recording_selection = QComboBox(self.widget_2)
        self.recording_selection.addItem("")
        self.recording_selection.addItem("")
        self.recording_selection.addItem("")
        self.recording_selection.addItem("")
        self.recording_selection.setObjectName(u"recording_selection")
        self.recording_selection.setGeometry(QRect(30, 90, 111, 31))
        self.widget = QWidget(self.widget_2)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(450, 20, 271, 51))
        self.timer = QLineEdit(self.widget)
        self.timer.setObjectName(u"timer")
        self.timer.setGeometry(QRect(10, 10, 101, 31))
        self.start = QPushButton(self.widget)
        self.start.setObjectName(u"start")
        self.start.setGeometry(QRect(130, 10, 51, 31))
        self.stop = QPushButton(self.widget)
        self.stop.setObjectName(u"stop")
        self.stop.setGeometry(QRect(200, 10, 51, 31))
        self.label = QLabel(self.widget_2)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(450, 90, 71, 21))
        self.label_2 = QLabel(self.widget_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(450, 130, 71, 16))
        self.save_path_show = QLineEdit(self.widget_2)
        self.save_path_show.setObjectName(u"save_path_show")
        self.save_path_show.setGeometry(QRect(530, 90, 201, 21))
        self.shot_save_path_show = QLineEdit(self.widget_2)
        self.shot_save_path_show.setObjectName(u"shot_save_path_show")
        self.shot_save_path_show.setGeometry(QRect(530, 130, 201, 21))
        self.label_3 = QLabel(self.widget_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 160, 51, 31))
        self.screen_shot = QPushButton(self.widget_2)
        self.screen_shot.setObjectName(u"screen_shot")
        self.screen_shot.setGeometry(QRect(100, 160, 41, 31))
        self.pushButton_4 = QPushButton(self.widget_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(690, 190, 41, 31))
        self.widget_3 = QWidget(self.widget_2)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 250, 721, 401))
        self.pushButton_5 = QPushButton(self.widget_3)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(10, 10, 111, 41))
        self.pushButton_6 = QPushButton(self.widget_3)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(10, 70, 111, 41))
        self.pushButton_8 = QPushButton(self.widget_3)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(10, 130, 111, 41))
        self.pushButton_9 = QPushButton(self.widget_3)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(10, 190, 111, 41))
        self.pushButton_10 = QPushButton(self.widget_3)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(10, 250, 111, 41))
        self.tabWidget = QTabWidget(self.widget_3)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(140, 10, 541, 351))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setTabletTracking(False)
        self.tabWidget.setFocusPolicy(Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(Qt.NoContextMenu)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QTabWidget.West)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setElideMode(Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.video_dir = QWidget()
        self.video_dir.setObjectName(u"video_dir")
        self.tabWidget.addTab(self.video_dir, "")
        self.shot_dir = QWidget()
        self.shot_dir.setObjectName(u"shot_dir")
        self.tabWidget.addTab(self.shot_dir, "")
        self.camera = QWidget()
        self.camera.setObjectName(u"camera")
        self.tabWidget.addTab(self.camera, "")
        self.setting = QWidget()
        self.setting.setObjectName(u"setting")
        self.tabWidget.addTab(self.setting, "")
        self.other_tools = QWidget()
        self.other_tools.setObjectName(u"other_tools")
        self.tabWidget.addTab(self.other_tools, "")

        self.retranslateUi(VideoRecording)

        self.tabWidget.setCurrentIndex(4)


        QMetaObject.connectSlotsByName(VideoRecording)
    # setupUi

    def retranslateUi(self, VideoRecording):
        VideoRecording.setWindowTitle(QCoreApplication.translate("VideoRecording", u"Form", None))
        self.recording_screen_selection.setItemText(0, QCoreApplication.translate("VideoRecording", u"\u5168\u5c4f\u5f55\u5236", None))
        self.recording_screen_selection.setItemText(1, QCoreApplication.translate("VideoRecording", u"\u533a\u57df\u5f55\u5236", None))
        self.recording_screen_selection.setItemText(2, QCoreApplication.translate("VideoRecording", u"\u53ea\u5f55\u6444\u50cf\u5934", None))

        self.recording_selection.setItemText(0, QCoreApplication.translate("VideoRecording", u"\u4ec5\u9ea6\u514b\u98ce", None))
        self.recording_selection.setItemText(1, QCoreApplication.translate("VideoRecording", u"\u4ec5\u7cfb\u7edf\u58f0\u97f3", None))
        self.recording_selection.setItemText(2, QCoreApplication.translate("VideoRecording", u"\u7cfb\u7edf\u4e0e\u9ea6\u514b\u98ce", None))
        self.recording_selection.setItemText(3, QCoreApplication.translate("VideoRecording", u"\u4e0d\u5f55\u5236\u58f0\u97f3", None))

        self.timer.setText(QCoreApplication.translate("VideoRecording", u"00\uff1a00\uff1a00", None))
        self.start.setText(QCoreApplication.translate("VideoRecording", u"\u5f00\u59cb", None))
        self.stop.setText(QCoreApplication.translate("VideoRecording", u"\u505c\u6b62", None))
        self.label.setText(QCoreApplication.translate("VideoRecording", u"\u4fdd\u5b58\u8def\u5f84", None))
        self.label_2.setText(QCoreApplication.translate("VideoRecording", u"\u622a\u56fe\u8def\u5f84", None))
        self.label_3.setText(QCoreApplication.translate("VideoRecording", u"\u622a\u5c4f", None))
        self.screen_shot.setText(QCoreApplication.translate("VideoRecording", u"\u622a", None))
        self.pushButton_4.setText(QCoreApplication.translate("VideoRecording", u"\u4e0b\u62c9", None))
        self.pushButton_5.setText(QCoreApplication.translate("VideoRecording", u"\u89c6\u9891", None))
        self.pushButton_6.setText(QCoreApplication.translate("VideoRecording", u"\u622a\u56fe", None))
        self.pushButton_8.setText(QCoreApplication.translate("VideoRecording", u"\u6444\u50cf\u5934", None))
        self.pushButton_9.setText(QCoreApplication.translate("VideoRecording", u"\u8bbe\u7f6e", None))
        self.pushButton_10.setText(QCoreApplication.translate("VideoRecording", u"\u5176\u4ed6\u5de5\u5177", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.video_dir), QCoreApplication.translate("VideoRecording", u"\u89c6\u9891", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.shot_dir), QCoreApplication.translate("VideoRecording", u"\u622a\u56fe", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.camera), QCoreApplication.translate("VideoRecording", u"\u6444\u50cf\u5934", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setting), QCoreApplication.translate("VideoRecording", u"\u8bbe\u7f6e", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.other_tools), QCoreApplication.translate("VideoRecording", u"\u5176\u4ed6\u5de5\u5177", None))
    # retranslateUi

